### ISSUE TITLE
About step size β

### ISSUE THREAD

**Issue by zhiqihuang** [johncava/pytorch-IPOT#1]
I think [here](https://github.com/johncava/pytorch-IPOT/blob/fdff12e7ffe3476813c77733d737f14de713b4c0/ipot.py#L15) should be  `A = torch.exp(-C / beta)`

**Comment by johncava** [comment]
The code has been updated. Thanks for the catch!

**Comment by zhiqihuang** [comment]
Thanks for your implementation. Is it possible to do the batch IPOT computation? For example the cost matrix C.size() = (batch_size, n, m)

**Comment by johncava** [comment]
> Thanks for your implementation. Is it possible to do the batch IPOT computation? For example the cost matrix C.size() = (batch_size, n, m)

@zhiqihuang I'm not 100% sure, but I believe it is possible to have T in line 9 be batched with batched matrix multiplication, but also what is needed would be the batched matrix multiplication of line 23. Regardless C[i,j] has to be done through a for loop, as this is traditional dynamic programming cost function, and even if C would be the size of (batch_size, n,m), the nature of the cost matrix, must make it such that another for loop must be added for indexing the batched input. 

I would personally use a sequential model with batched input, and then index pairs within that batch with the ipot(x,y) function, and backward propagate from there.

**Comment by zhiqihuang** [comment]
> > Thanks for your implementation. Is it possible to do the batch IPOT computation? For example the cost matrix C.size() = (batch_size, n, m)
> 
> @zhiqihuang I'm not 100% sure, but I believe it is possible to have T in line 9 be batched with batched matrix multiplication, but also what is needed would be the batched matrix multiplication of line 23. Regardless C[i,j] has to be done through a for loop, as this is traditional dynamic programming cost function, and even if C would be the size of (batch_size, n,m), the nature of the cost matrix, must make it such that another for loop must be added for indexing the batched input.
> 
> I would personally use a sequential model with batched input, and then index pairs within that batch with the ipot(x,y) function, and backward propagate from there.

Thanks. I tested the sequential training approach. It runs pretty fast.

**Comment by zhiqihuang** [comment]
Hi, 
Sorry to bother you again. I just found that [here](https://github.com/johncava/pytorch-IPOT/blob/fcdc3fee50e85dfa334b212643fd5a43bb6a7db7/ipot.py#L30), instead of `trace`, to compute the `distance`, we should use `torch.sum(C.t().mm(T))`.  Because `trace` is the sum of the elements of the diagonal, the results are only the distance of ith element in `x` to ith element in `y`.

NVM, it's `C` transpose. I misunderstood it with the element-wise product.
